import React,{useState,useEffect,useRef}from'react';
import{Folder,FolderPlus,FileText,MoreHorizontal,Home,ChevronRight,ArrowUp,Search,List,Grid2X2,Pencil,FolderInput,Copy,Trash2,ExternalLink,X,Star}from'lucide-react';
import{libraryRepository}from'./library-repository';import{breadcrumbs,extension,descendants,docFromEntry,formatSize}from'./library-model';import FolderPicker from'./FolderPicker';import PdfThumbnail from'./PdfThumbnail';import'./explorer.css';
export default function FileExplorer({entries,currentFolder,onFolderChange,onOpen,onChanged,onNotice,repository=libraryRepository}){
 const[search,setSearch]=useState(''),[view,setView]=useState('list'),[sort,setSort]=useState('name'),[selected,setSelected]=useState(null),[context,setContext]=useState(null),[dialog,setDialog]=useState(null),[name,setName]=useState(''),[destination,setDestination]=useState(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 const press=useRef(null),suppress=useRef(0),actionLock=useRef(false),menuRef=useRef(null);
 const trail=breadcrumbs(entries,currentFolder),current=entries.find(e=>e.id===currentFolder);
 useEffect(()=>{setSelected(null);setContext(null);setSearch('')},[currentFolder]);
 useEffect(()=>{if(!context)return;const close=()=>setContext(null),escape=e=>{if(e.key==='Escape')close()};document.addEventListener('click',close);document.addEventListener('keydown',escape);menuRef.current?.querySelector('button')?.focus();return()=>{document.removeEventListener('click',close);document.removeEventListener('keydown',escape)}},[context]);
 useEffect(()=>()=>clearTimeout(press.current?.timer),[]);
 const visible=entries.filter(e=>e.parentId===currentFolder&&(!search||e.name.toLocaleLowerCase().includes(search.toLocaleLowerCase()))).sort((a,b)=>a.type!==b.type?(a.type==='folder'?-1:1):sort==='updated'?b.updatedAt.localeCompare(a.updatedAt):sort==='size'?(b.sizeBytes||0)-(a.sizeBytes||0):a.name.localeCompare(b.name,'ja'));
 const selectedEntry=entries.find(e=>e.id===selected),menuEntry=entries.find(e=>e.id===context?.id);
 async function perform(action,message){if(actionLock.current)return;actionLock.current=true;setBusy(true);setError('');try{const result=await action();onChanged(result);setDialog(null);setContext(null);onNotice(message);return true}catch(e){setError(e.message||'操作に失敗しました。');return false}finally{actionLock.current=false;setBusy(false)}}
 function open(entry){if(entry.type==='folder')onFolderChange(entry.id);else onOpen(entry.id)}
 function showMenu(event,entry){event.preventDefault();event.stopPropagation();setSelected(entry.id);setContext({id:entry.id,x:Math.max(8,Math.min(event.clientX,window.innerWidth-220)),y:Math.max(8,Math.min(event.clientY,window.innerHeight-285))})}
 function touchStart(event,entry){if(event.pointerType==='mouse')return;clearTimeout(press.current?.timer);const x=event.clientX,y=event.clientY;press.current={x,y,timer:setTimeout(()=>{suppress.current=Date.now()+900;setSelected(entry.id);setContext({id:entry.id,x:Math.max(8,Math.min(x,window.innerWidth-220)),y:Math.max(8,Math.min(y,window.innerHeight-285))})},550)}}
 function cancelPress(event){if(!event||!press.current||Math.hypot(event.clientX-press.current.x,event.clientY-press.current.y)>10)clearTimeout(press.current?.timer)}
 function startDialog(type,entry){setContext(null);setError('');setDialog({type,entry});const ext=entry?.type==='file'?extension(entry.name):'';setName(type==='create'?'':ext?entry.name.slice(0,-ext.length):entry?.name||'');setDestination(entry?.parentId??currentFolder)}
 async function submit(e){e.preventDefault();if(dialog.type==='create')await perform(()=>repository.createFolder(currentFolder,name),'フォルダを作成しました');else if(dialog.type==='rename')await perform(()=>repository.rename(dialog.entry.id,name),'名前を変更しました');else if(dialog.type==='move')await perform(()=>repository.move(dialog.entry.id,destination),'移動しました');else if(dialog.type==='delete')await perform(()=>repository.remove(dialog.entry.id),'削除しました')}
 function drop(event,target){event.preventDefault();event.stopPropagation();try{const raw=event.dataTransfer.getData('application/x-folio-id');if(!raw)return;const id=JSON.parse(raw);perform(()=>repository.move(id,target),'移動しました')}catch{setError('移動する項目を確認してください。')}}
 function actionButtons(entry){return <><button role="menuitem" onClick={()=>{setContext(null);open(entry)}}><ExternalLink size={16}/>開く</button><button role="menuitem" onClick={()=>startDialog('rename',entry)}><Pencil size={16}/>名前変更</button><button role="menuitem" onClick={()=>startDialog('move',entry)}><FolderInput size={16}/>移動</button><button role="menuitem" onClick={()=>perform(()=>repository.duplicate(entry.id),'複製しました')}><Copy size={16}/>複製</button><button role="menuitem" className="danger" onClick={()=>startDialog('delete',entry)}><Trash2 size={16}/>削除</button></>}
 const deleting=dialog?.type==='delete'?entries.filter(e=>descendants(entries,dialog.entry.id).has(e.id)):[];
 return <section className="explorer" aria-label="ファイル管理" aria-busy={busy}>
  <div className="explorer-heading"><div><h2><Folder size={21}/>{current?.name||'マイファイル'}</h2><p>資料をフォルダに整理して、自分だけのライブラリに。</p></div><button className="primary" disabled={busy} onClick={()=>startDialog('create')}><FolderPlus size={17}/>新しいフォルダ</button></div>
  <nav className="folder-trail explorer-trail" aria-label="現在のフォルダ"><button aria-label="上のフォルダへ" disabled={currentFolder===null} onClick={()=>onFolderChange(current?.parentId??null)}><ArrowUp size={16}/></button><button onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,null)} onClick={()=>onFolderChange(null)}><Home size={14}/>ホーム</button>{trail.map(e=><React.Fragment key={e.id}><ChevronRight size={13}/><button onDragOver={event=>event.preventDefault()} onDrop={event=>drop(event,e.id)} onClick={()=>onFolderChange(e.id)} aria-current={e.id===currentFolder?'location':undefined}>{e.name}</button></React.Fragment>)}</nav>
  <div className="explorer-toolbar"><label className="search"><Search size={16}/><input aria-label="このフォルダを検索" placeholder="このフォルダを検索" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="ファイルの並び順" value={sort} onChange={e=>setSort(e.target.value)}><option value="name">名前順</option><option value="updated">更新日時順</option><option value="size">サイズ順</option></select><div className="view-toggle"><button aria-label="一覧表示" className={view==='list'?'selected':''} onClick={()=>setView('list')}><List size={17}/></button><button aria-label="グリッド表示" className={view==='grid'?'selected':''} onClick={()=>setView('grid')}><Grid2X2 size={17}/></button></div></div>
  <div className="selection-toolbar"><span>{selectedEntry?selectedEntry.name:`${visible.length} 項目`}</span>{selectedEntry&&<><button aria-label="選択項目の名前変更" onClick={()=>startDialog('rename',selectedEntry)}><Pencil size={15}/><span>名前変更</span></button><button aria-label="選択項目の移動" onClick={()=>startDialog('move',selectedEntry)}><FolderInput size={15}/><span>移動</span></button><button aria-label="選択項目の複製" onClick={()=>perform(()=>repository.duplicate(selectedEntry.id),'複製しました')}><Copy size={15}/><span>複製</span></button><button aria-label="選択項目の削除" onClick={()=>startDialog('delete',selectedEntry)}><Trash2 size={15}/><span>削除</span></button></>}</div>
  {error&&!dialog&&<div className="explorer-error" role="alert">{error}<button aria-label="エラーを閉じる" onClick={()=>setError('')}><X size={15}/></button></div>}
  <div className={'entry-list '+(view==='grid'?'entry-grid':'')} onDragOver={e=>e.preventDefault()} onDrop={e=>drop(e,currentFolder)}>{view==='list'&&<div className="entry-head"><span>名前</span><span>更新日時</span><span>種類</span><span>サイズ</span><span/></div>}{visible.map(entry=><div key={entry.id} className={'entry-row '+(selected===entry.id?'is-selected':'')} data-entry-id={entry.id} data-entry-name={entry.name} tabIndex={0} role="group" aria-label={entry.name} draggable={!busy} onDragStart={e=>{e.dataTransfer.setData('application/x-folio-id',JSON.stringify(entry.id));e.dataTransfer.effectAllowed='move';setSelected(entry.id);setContext(null)}} onDragOver={e=>{if(entry.type==='folder')e.preventDefault()}} onDrop={e=>{if(entry.type==='folder')drop(e,entry.id)}} onClick={()=>setSelected(entry.id)} onDoubleClick={()=>open(entry)} onClickCapture={e=>{if(Date.now()<suppress.current){e.preventDefault();e.stopPropagation()}}} onContextMenu={e=>showMenu(e,entry)} onPointerDown={e=>touchStart(e,entry)} onPointerMove={cancelPress} onPointerUp={()=>cancelPress()} onPointerCancel={()=>cancelPress()} onKeyDown={e=>{if(e.target!==e.currentTarget)return;if(e.key==='Enter')open(entry);if(e.key==='F2'){e.preventDefault();startDialog('rename',entry)}if(e.key==='Delete')startDialog('delete',entry);if(e.key==='ContextMenu'||(e.shiftKey&&e.key==='F10')){const r=e.currentTarget.getBoundingClientRect();showMenu({preventDefault:()=>e.preventDefault(),stopPropagation:()=>e.stopPropagation(),clientX:r.left+24,clientY:r.top+24},entry)}}}>
   <button className="entry-open" onClick={e=>{e.stopPropagation();open(entry)}} aria-label={entry.name}>{view==='grid'&&entry.type==='file'&&entry.storedPdf?<div className="entry-thumb"><PdfThumbnail doc={docFromEntry(entry)}/></div>:entry.type==='folder'?<Folder className="folder-icon" size={view==='grid'?52:23} fill="currentColor" strokeWidth={1.2}/>:<FileText className="pdf-icon" size={view==='grid'?44:23}/>}<span>{entry.name}{entry.star&&<Star size={11}/>}</span></button>
   <span className="entry-date">{new Date(entry.updatedAt).toLocaleDateString('ja-JP')}</span><span className="entry-type">{entry.type==='folder'?'フォルダ':entry.storedPdf?'PDF':entry.mimeType==='application/pdf'?'PDF':'サンプル'}</span><span className="entry-size">{entry.type==='folder'?'—':formatSize(entry.sizeBytes)}</span><button className="entry-more" aria-label={`${entry.name}の操作`} onClick={e=>showMenu(e,entry)}><MoreHorizontal size={19}/></button>
  </div>)}{!visible.length&&<div className="explorer-empty"><Folder size={40}/><h3>{search?'項目が見つかりません':'このフォルダは空です'}</h3><p>「新しいフォルダ」や「資料を追加」から整理を始めましょう。</p></div>}</div>
  <p className="explorer-help">右クリック・長押し・「…」で操作できます。フォルダやパンくずへのドラッグで移動できます。</p>
  {context&&menuEntry&&<div ref={menuRef} className="entry-context" role="menu" aria-label="項目の操作" style={{left:context.x,top:context.y}} onClick={e=>e.stopPropagation()}>{actionButtons(menuEntry)}</div>}
  {dialog&&<div className="explorer-overlay"><section className="explorer-dialog" role="dialog" aria-modal="true" aria-label={dialog.type==='create'?'フォルダを作成':dialog.type==='rename'?'名前を変更':dialog.type==='move'?'項目を移動':'削除の確認'}><button className="close" disabled={busy} aria-label="操作をキャンセル" onClick={()=>{setDialog(null);setError('')}}><X size={20}/></button><h2>{dialog.type==='create'?'新しいフォルダ':dialog.type==='rename'?'名前を変更':dialog.type==='move'?'移動先を選択':'削除しますか？'}</h2><form onSubmit={submit}>
   {(dialog.type==='create'||dialog.type==='rename')&&<label className="name-field">{dialog.type==='create'?'フォルダ名':'名前'}<div><input autoFocus required aria-label={dialog.type==='create'?'フォルダ名':'新しい名前'} value={name} onChange={e=>setName(e.target.value)}/>{dialog.entry?.type==='file'&&<span>{extension(dialog.entry.name)}</span>}</div>{dialog.entry?.type==='file'&&<small>拡張子は変更されません。</small>}</label>}
   {dialog.type==='move'&&<FolderPicker entries={entries} value={destination} onChange={setDestination} excludeId={dialog.entry.id} label="移動先フォルダ"/>}
   {dialog.type==='delete'&&<><p>「{dialog.entry.name}」を削除します。</p>{dialog.entry.type==='folder'&&<p>配下のフォルダ {deleting.filter(e=>e.type==='folder').length-1} 件と、ファイル {deleting.filter(e=>e.type==='file').length} 件も削除されます。</p>}<p>PDF本体・注釈・下書きも削除します。この操作は取り消せません。</p></>}
   {error&&<p className="explorer-error" role="alert">{error}</p>}<div className="explorer-dialog-actions"><button type="button" disabled={busy} onClick={()=>{setDialog(null);setError('')}}>キャンセル</button><button className={'primary '+(dialog.type==='delete'?'delete-confirm':'')} disabled={busy} type="submit">{busy?'処理中…':dialog.type==='create'?'作成する':dialog.type==='rename'?'変更する':dialog.type==='move'?'移動する':'削除する'}</button></div>
  </form></section></div>}
 </section>
}
