// Storage-independent tree rules. Identity never depends on a display path.
export const ROOT = null;
export const timestamp = () => new Date().toISOString();
export function cleanName(value){const name=String(value??'').normalize('NFC').trim();if(!name||name==='.'||name==='..')throw Error('名前を入力してください。');if(/[\\/:*?"<>|\u0000-\u001f]/u.test(name)||name.endsWith('.'))throw Error('名前に使用できない文字が含まれています。');if([...name].length>255)throw Error('名前は255文字以内にしてください。');return name}
const nameKey=value=>value.normalize('NFC').toLocaleLowerCase('ja');
export function extension(name){const at=name.lastIndexOf('.');return at>0?name.slice(at):''}
export function assertParent(entries,parentId){if(parentId!==null&&!entries.some(e=>e.id===parentId&&e.type==='folder'))throw Error('保存先フォルダが見つかりません。');}
export function assertUnique(entries,name,parentId,exceptId){if(entries.some(e=>e.parentId===parentId&&e.id!==exceptId&&nameKey(e.name)===nameKey(name)))throw Error('同じ場所に同名のファイルまたはフォルダがあります。別の名前を入力してください。');}
export function uniqueName(entries,name,parentId,copy=false){const ext=extension(name),stem=ext?name.slice(0,-ext.length):name;let n=copy?1:0;while(true){const suffix=copy?`（コピー${n===1?'':n}）`:`（${n+1}）`;const candidate=n===0?name:`${[...stem].slice(0,Math.max(0,255-[...suffix].length-[...ext].length)).join('')}${suffix}${ext}`;if(!entries.some(e=>e.parentId===parentId&&nameKey(e.name)===nameKey(candidate)))return candidate;n++}}
export function descendants(entries,id){const children=new Map();for(const e of entries){if(!children.has(e.parentId))children.set(e.parentId,[]);children.get(e.parentId).push(e.id)}const found=new Set(),queue=[id];for(let i=0;i<queue.length;i++){const current=queue[i];if(found.has(current))continue;found.add(current);queue.push(...(children.get(current)||[]))}return found}
export function assertMove(entries,id,parentId){assertParent(entries,parentId);if(descendants(entries,id).has(parentId))throw Error('自分自身や配下のフォルダには移動できません。');const entry=entries.find(e=>e.id===id);if(!entry)throw Error('項目が見つかりません。');assertUnique(entries,entry.name,parentId,id)}
export function breadcrumbs(entries,id){const byId=new Map(entries.map(e=>[e.id,e])),trail=[],seen=new Set();let cursor=id;while(cursor!==null){if(seen.has(cursor))throw Error('フォルダ階層が循環しています。');seen.add(cursor);const entry=byId.get(cursor);if(!entry)break;trail.push(entry);cursor=entry.parentId}return trail.reverse()}
export function entryFromDoc(doc){const {title,type,mime,size,...rest}=doc;const real=doc.storedPdf||mime==='application/pdf';const name=real&&!/\.pdf$/i.test(title)?title+'.pdf':title;const date=doc.date&&Number.isFinite(Date.parse(doc.date))?new Date(doc.date).toISOString():timestamp();return {...rest,id:doc.id,name,type:'file',category:type||'講義資料',parentId:doc.parentId??null,createdAt:doc.createdAt||date,updatedAt:doc.updatedAt||date,mimeType:mime||(real?'application/pdf':'application/x-folio-sample'),sizeBytes:doc.sizeBytes??null,sizeLabel:size,storage:{provider:real?'indexeddb':'sample',key:doc.id},originalName:doc.originalName||title}}
export function docFromEntry(entry){return {...entry,type:entry.category||'講義資料',kind:'file',title:entry.name,mime:entry.mimeType,size:entry.sizeLabel||formatSize(entry.sizeBytes),date:entry.updatedAt.slice(0,10)}}
export function formatSize(bytes){if(bytes==null)return '—';return bytes<1048576?`${Math.max(1,Math.round(bytes/1024))} KB`:`${(bytes/1048576).toFixed(1)} MB`}
