import {isNativeApp} from './mobile-runtime';
import FolderPicker from './FolderPicker';
import {cleanName} from './library-model';
import {libraryRepository} from './library-repository';
import {externalStorage,externalSaveError} from './external-storage';
import React,{useState,useEffect,useRef,useReducer} from 'react';
import {getDocument,GlobalWorkerOptions} from 'pdfjs-dist/legacy/build/pdf.mjs';
import workerUrl from 'pdfjs-dist/legacy/build/pdf.worker.min.mjs?url';
import {ChevronLeft,ChevronRight,Undo2,Redo2,Eraser,Pen,Highlighter,Hand,Download,Trash2,X,ZoomIn,ZoomOut,Save} from 'lucide-react';
import {read,write,remove,readDraft,clearFastDraft} from './storage';
import {bakeAnnotations} from './pdf-export';
import {normalizedPoint,drawStrokes,changeHistory,eraseStrokes} from './annotations';
import './pdf.css';
GlobalWorkerOptions.workerSrc=workerUrl;
export default function PdfViewer({doc,entries=[],onClose,onSaved,onDelete}){
 const [exportBlob,setExportBlob]=useState(null),[exportPreparing,setExportPreparing]=useState(false),[saveNotice,setSaveNotice]=useState('');
 const [saveName,setSaveName]=useState(doc.title.replace(/\.pdf$/i,''));
 const [saveTarget,setSaveTarget]=useState('internal'),[saveFolder,setSaveFolder]=useState(doc.parentId??null),[saveError,setSaveError]=useState('');
 const [showNotes,setShowNotes]=useState(false),[pdf,setPdf]=useState(null),[error,setError]=useState(''),[page,setPage]=useState(1),[zoom,setZoom]=useState(1),[tool,setTool]=useState('pen'),[color,setColor]=useState('#c8f542'),[penColor,setPenColor]=useState('#244b3f'),[width,setWidth]=useState(20),[opacity,setOpacity]=useState(.4),[memorize,setMemorize]=useState(false),[history,dispatch]=useReducer(changeHistory,{past:[],present:{},future:[]}),[note,setNote]=useState(doc.note||''),[loaded,setLoaded]=useState(false),[status,setStatus]=useState('読み込み中'),[ready,setReady]=useState(false),[size,setSize]=useState({width:600,height:800}),[containerWidth,setContainerWidth]=useState(700),[recovery,setRecovery]=useState(null),[saveDialog,setSaveDialog]=useState(false),[saving,setSaving]=useState(false);
 const erasing=useRef(null);
 const pdfCanvas=useRef(null),inkCanvas=useRef(null),area=useRef(null),active=useRef(null),latest=useRef({}),saveQueue=useRef(Promise.resolve()),blobRef=useRef(null),baseline=useRef({pages:{},note:doc.note||''}),draftSequence=useRef(0),mounted=useRef(true),busy=useRef(false);
 latest.current={history,memorize,ready,page,note};
 const revision=doc.revision||'legacy';
 useEffect(()=>{let alive=true,task;mounted.current=true;
  async function load(){try{const blob=await libraryRepository.loadFile(doc);if(!blob)throw Error('PDFファイルが見つかりません。もう一度追加してください。');blobRef.current=blob;task=getDocument({data:new Uint8Array(await blob.arrayBuffer()),isEvalSupported:false});task.onPassword=()=>{setError('パスワード付きPDFには対応していません。解除したPDFを追加してください。');task.destroy()};const [file,annotations,draft]=await Promise.all([task.promise,read('annotations',doc.id),readDraft(doc.id)]);if(alive){baseline.current={pages:annotations?.pages||{},note:doc.note||''};setPdf(file);dispatch({type:'reset',value:baseline.current.pages});if(draft)setRecovery(draft);setLoaded(true);setStatus(draft?'未保存の編集があります':'保存済み')}}catch(e){if(alive)setError(e.message||'PDFを読み込めませんでした。')}}load();return()=>{alive=false;mounted.current=false;task?.destroy()};
 },[doc.id]);
 useEffect(()=>{const ro=new ResizeObserver(entries=>setContainerWidth(Math.max(200,entries[0].contentRect.width-48)));ro.observe(area.current);return()=>ro.disconnect()},[]);
 useEffect(()=>{if(!pdf)return;let cancelled=false,renderTask;setReady(false);if(erasing.current){dispatch({type:'set',value:erasing.current.pages});erasing.current=null;}if(active.current){const snapshot=latest.current;dispatch({type:'set',value:{...snapshot.history.present,[snapshot.page]:[...(snapshot.history.present[snapshot.page]||[]),active.current.stroke]}});active.current=null;}
  async function render(){try{const p=await pdf.getPage(page);if(cancelled)return;const viewport=p.getViewport({scale:Math.min(containerWidth/p.getViewport({scale:1}).width,1.4)*zoom});const canvas=pdfCanvas.current,dpr=Math.min(window.devicePixelRatio||1,2);canvas.width=Math.round(viewport.width*dpr);canvas.height=Math.round(viewport.height*dpr);inkCanvas.current.width=canvas.width;inkCanvas.current.height=canvas.height;setSize({width:viewport.width,height:viewport.height});renderTask=p.render({canvasContext:canvas.getContext('2d'),viewport,transform:[dpr,0,0,dpr,0,0]});await renderTask.promise;if(!cancelled){setReady(true);drawStrokes(inkCanvas.current,latest.current.history.present[page]||[],latest.current.memorize)}}catch(e){if(!cancelled&&e.name!=='RenderingCancelledException')setError('ページの描画に失敗しました。')}}render();return()=>{cancelled=true;renderTask?.cancel()};
 },[pdf,page,zoom,containerWidth]);
 useEffect(()=>{if(inkCanvas.current&&ready)drawStrokes(inkCanvas.current,history.present[page]||[],memorize)},[history.present,page,memorize,ready]);
 function persistDraft(pages,currentNote){if(busy.current)return;const sequence=++draftSequence.current;const unchanged=JSON.stringify({pages,note:currentNote})===JSON.stringify(baseline.current);const draft={version:1,baseRevision:revision,updatedAt:Date.now(),pages,note:currentNote};
  // Synchronous crash journal covers an in-flight IndexedDB transaction, including an unfinished stroke.
  try{if(unchanged)clearFastDraft(doc.id);else localStorage.setItem('folio-draft-'+doc.id,JSON.stringify(draft))}catch{/* IndexedDB remains the primary draft store. */}
  setStatus(unchanged?'保存済み':'下書きを退避中…');
  saveQueue.current=saveQueue.current.catch(()=>{}).then(()=>unchanged?remove('drafts',doc.id):write('drafts',doc.id,draft));
  saveQueue.current.then(()=>{if(mounted.current&&sequence===draftSequence.current)setStatus(unchanged?'保存済み':'下書きを端末に退避しました')},()=>{if(mounted.current)setStatus('保存失敗：端末の空き容量を確認してください')});
 }
 useEffect(()=>{if(loaded&&!recovery)persistDraft(history.present,note)},[history.present,note,loaded,recovery]);
 function redraw(){drawStrokes(inkCanvas.current,[...(latest.current.history.present[page]||[]),...(active.current?[active.current.stroke]:[])],memorize)}
 function draftActive(){persistDraft({...latest.current.history.present,[page]:[...(latest.current.history.present[page]||[]),active.current.stroke]},latest.current.note)}
 function eraseAt(e){const rect=e.currentTarget.getBoundingClientRect(),point=normalizedPoint(e,rect),gesture=erasing.current;gesture.pages={...gesture.pages,[page]:eraseStrokes(gesture.pages[page]||[],gesture.last,point,12/rect.width,rect.height/rect.width)};gesture.last=point;persistDraft(gesture.pages,note);drawStrokes(inkCanvas.current,gesture.pages[page]||[],false)}
 function start(e){if(!ready||tool==='hand'||memorize||recovery||saving||saveDialog||active.current||erasing.current||!e.isPrimary||e.button!==0)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);const rect=e.currentTarget.getBoundingClientRect();if(tool==='eraser'){erasing.current={pointerId:e.pointerId,pages:history.present,last:normalizedPoint(e,rect)};eraseAt(e);return}active.current={pointerId:e.pointerId,stroke:{id:crypto.randomUUID(),memorize:tool==='memorize',color:tool==='memorize'?color:penColor,opacity:tool==='memorize'?opacity:1,width:(tool==='memorize'?width:Math.max(1,width/6))/600,points:[normalizedPoint(e,rect)]}};draftActive();redraw()}
 function move(e){if(erasing.current?.pointerId===e.pointerId){e.preventDefault();eraseAt(e);return}if(active.current?.pointerId!==e.pointerId)return;e.preventDefault();const rect=e.currentTarget.getBoundingClientRect(),events=e.nativeEvent.getCoalescedEvents?.();for(const event of events?.length?events:[e])active.current.stroke.points.push(normalizedPoint(event,rect));draftActive();redraw()}
 function end(e,cancel=false){if(erasing.current?.pointerId===e.pointerId){const pages=erasing.current.pages;erasing.current=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);if(!cancel&&JSON.stringify(pages)!==JSON.stringify(history.present))dispatch({type:'set',value:pages});else{persistDraft(history.present,note);redraw()}return}if(active.current?.pointerId!==e.pointerId)return;const stroke=active.current.stroke;if(!cancel)stroke.points.push(normalizedPoint(e,e.currentTarget.getBoundingClientRect()));active.current=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);if(!cancel)dispatch({type:'set',value:{...history.present,[page]:[...(history.present[page]||[]),stroke]}});else{persistDraft(history.present,note);redraw()}}
 async function chooseRecovery(restore){if(busy.current)return;try{if(restore){dispatch({type:'set',value:recovery.pages});setNote(recovery.note??doc.note??'')}else{await remove('drafts',doc.id);clearFastDraft(doc.id)}setRecovery(null)}catch{setStatus('下書きの処理に失敗しました。再試行してください。')}}
 async function save(mode){if(busy.current||!pdf)return;busy.current=true;setSaving(true);setSaveError('');setStatus('保存中…');try{const name=cleanName(cleanName(saveName)+'.pdf');await saveQueue.current.catch(()=>{});const blob=mode==='delta'?null:await bakeAnnotations(blobRef.current,pdf,history.present);const result=await libraryRepository.saveEdition(doc,mode,history.present,note,blob,{parentId:saveFolder,name:name===doc.title?undefined:name});onSaved(result)}catch(e){setSaveError(e.message||'もう一度お試しください');setStatus('保存失敗：'+(e.message||'もう一度お試しください'));setSaving(false);busy.current=false}}
 useEffect(()=>{if(!saveDialog||saveTarget!=='external'||!pdf)return;let cancelled=false;setExportBlob(null);setExportPreparing(true);setSaveError('');setSaveNotice('');bakeAnnotations(blobRef.current,pdf,history.present).then(blob=>{if(!cancelled)setExportBlob(blob)}).catch(e=>{if(!cancelled)setSaveError(externalSaveError(e,'generate'))}).finally(()=>{if(!cancelled)setExportPreparing(false)});return()=>{cancelled=true}},[saveDialog,saveTarget,pdf,history.present]);
 async function saveExternal(){if(busy.current||!exportBlob)return;busy.current=true;setSaving(true);setSaveError('');setSaveNotice('');try{const name=cleanName(cleanName(saveName)+'.pdf');const message=await externalStorage.write({kind:'download',name},exportBlob);setSaveError('');setStatus(message);setSaveDialog(false)}catch(e){setSaveError(externalSaveError(e,'write'));setStatus('外部保存に失敗しました。下書きは保持しています。')}finally{busy.current=false;setSaving(false)}}
 async function download(){if(busy.current)return;busy.current=true;setSaving(true);try{setStatus(await externalStorage.write({kind:'download',name:doc.title},blobRef.current))}catch(e){setStatus(externalSaveError(e,'write'))}finally{busy.current=false;setSaving(false)}}
 return <div className="pdf-viewer" role="dialog" aria-modal="true" aria-label="PDFと手書きメモ">
  <div className="pdf-header"><div><span>PDF LIBRARY</span><h2>{doc.title}</h2></div><span className={'pdf-save '+(status.startsWith('保存失敗')?'failed':'')} role="status">{status}</span><button aria-label="編集を保存" disabled={!loaded||!!recovery||saving} onClick={()=>{setSaveError('');setSaveNotice('');setSaveName(doc.title.replace(/\.pdf$/i,''));setSaveDialog(true)}}><Save size={19}/><span>保存</span></button><button aria-label="元のPDFをダウンロード" disabled={!pdf||saving} onClick={download}><Download size={19}/></button><button aria-label="PDFを削除" disabled={saving} onClick={async()=>{if(!confirm('このPDFとすべての手書き・メモを削除しますか？'))return;try{busy.current=true;await saveQueue.current.catch(()=>{});await onDelete()}catch{busy.current=false;setStatus('削除に失敗しました')}}}><Trash2 size={18}/></button><button aria-label="PDFを閉じる" disabled={saving} onClick={async()=>{await saveQueue.current.catch(()=>{});onClose()}}><X/></button></div>
  <div className="pdf-toolbar"><div className="pdf-tools">{[[Hand,'hand','閲覧'],[Pen,'pen','ペン'],[Eraser,'eraser','消しゴム'],[Highlighter,'memorize','暗記マーカー']].map(([Icon,value,label])=><button key={value} disabled={memorize||saving} className={tool===value?'chosen':''} onClick={()=>setTool(value)}><Icon size={17}/>{label}</button>)}</div><label className="color-label">色<input type="color" aria-label="ストロークの色" value={tool==='memorize'?color:penColor} onChange={e=>tool==='memorize'?setColor(e.target.value):setPenColor(e.target.value)}/></label><label>太さ<input aria-label="線の太さ" type="range" min="6" max="60" value={width} onChange={e=>setWidth(Number(e.target.value))}/></label>{tool==='memorize'&&<label>不透明度<input aria-label="マーカーの不透明度" type="range" min="0.1" max="0.8" step="0.05" value={opacity} onChange={e=>setOpacity(Number(e.target.value))}/></label>}<div className="pdf-history"><button aria-label="Undo" disabled={!history.past.length||memorize||saving} onClick={()=>dispatch({type:'undo'})}><Undo2 size={18}/></button><button aria-label="Redo" disabled={!history.future.length||memorize||saving} onClick={()=>dispatch({type:'redo'})}><Redo2 size={18}/></button></div><label className="memorize-switch"><input type="checkbox" checked={memorize} onChange={e=>setMemorize(e.target.checked)}/>暗記モード</label></div>
  <div className="pdf-body"><div className="pdf-area" ref={area}>{error?<div role="alert" className="pdf-error">{error}</div>:<><div className="pdf-hint">{memorize?'暗記マーカーを黒で隠しています。解除すると元の色に戻ります。':tool==='hand'?'スクロールして閲覧できます。':tool==='eraser'?'なぞった手書き線を線単位で消します。元PDFの文字や埋め込み済みの線は消せません。':'指・ペン・マウスで書き込めます。スクロールするには「閲覧」を選択。'}</div><div className="pdf-sheet" style={{width:size.width,height:size.height}}><canvas ref={pdfCanvas}/><canvas ref={inkCanvas} className="annotation-canvas" style={{touchAction:tool==='hand'||memorize?'auto':'none',pointerEvents:tool==='hand'||memorize||saving||recovery?'none':'auto'}} onPointerDown={start} onPointerMove={move} onPointerUp={e=>end(e)} onPointerCancel={e=>end(e,true)} onLostPointerCapture={e=>end(e,true)}/>{!ready&&<div className="pdf-loading">PDFを読み込んでいます…</div>}</div></>}</div><aside className={showNotes?'pdf-notes visible':'pdf-notes'}><h3>このPDFのメモ</h3><p>手書きとは別に、気づきを残せます。</p><textarea aria-label="PDFのテキストメモ" disabled={saving||!!recovery} value={note} onChange={e=>{setNote(e.target.value);persistDraft(history.present,e.target.value)}} placeholder="復習したいポイントなど…"/><div className="pdf-note-help"><Highlighter size={18}/><strong>覚えたいところを、なぞる。</strong><p>暗記マーカーで書いた線だけが、暗記モードで黒くなります。色・太さ・不透明度は次に描く線に適用されます。</p><small>編集は下書きとして端末に自動退避します。「保存」から確定方法を選んでください。</small></div></aside></div>
  <div className="pdf-bottom"><button className="mobile-notes" onClick={()=>setShowNotes(s=>!s)}>{showNotes?'PDFへ':'メモ'}</button><button aria-label="前のページ" disabled={!pdf||page===1||saving} onClick={()=>setPage(p=>p-1)}><ChevronLeft size={18}/></button><span>{page} / {pdf?.numPages||'–'} ページ</span><button aria-label="次のページ" disabled={!pdf||page===pdf.numPages||saving} onClick={()=>setPage(p=>p+1)}><ChevronRight size={18}/></button><div/><button aria-label="縮小" disabled={zoom<=.5||saving} onClick={()=>setZoom(z=>Math.max(.5,z-.25))}><ZoomOut size={18}/></button><span>{Math.round(zoom*100)}%</span><button aria-label="拡大" disabled={zoom>=2.5||saving} onClick={()=>setZoom(z=>Math.min(2.5,z+.25))}><ZoomIn size={18}/></button></div>
  {recovery&&<div className="pdf-modal-overlay"><section className="pdf-action-dialog" role="alertdialog" aria-label="前回の編集を復元"><h2>前回の編集を復元しますか？</h2><p>{new Date(recovery.updatedAt).toLocaleString('ja-JP')} の未保存の手書き・メモが端末に残っています。復元するまでPDFには反映しません。</p>{recovery.baseRevision!==revision&&<p className="failed">保存済みPDFの版が変わったため、この下書きは復元できません。</p>}<div className="recovery-actions"><button onClick={()=>chooseRecovery(false)}>破棄して開く</button><button className="primary" disabled={recovery.baseRevision!==revision} onClick={()=>chooseRecovery(true)}>復元する</button></div></section></div>}
  {saveDialog&&<div className="pdf-modal-overlay"><section className="pdf-action-dialog" role="dialog" aria-label="保存方法"><h2>編集の保存方法</h2><p>ファイル名と保存先を選択してください。</p><label className="name-field">ファイル名<div><input aria-label="保存するファイル名" value={saveName} disabled={saving} onChange={e=>setSaveName(e.target.value)}/><span>.pdf</span></div><small>拡張子は変更されません。コピーの同名時には連番が付きます。</small></label><div className="save-destinations"><button disabled={saving} className={saveTarget==='internal'?'chosen':''} onClick={()=>setSaveTarget('internal')}>アプリ内</button><button disabled={saving} className={saveTarget==='external'?'chosen':''} onClick={()=>setSaveTarget('external')}>アプリ外のフォルダ</button></div>
  {saveTarget==='internal'?<><FolderPicker entries={entries} value={saveFolder} onChange={setSaveFolder}/><button className="save-option" disabled={saving} onClick={()=>save('delta')}><strong>① 変更分だけアプリに保存</strong><span>元PDFを維持。選択したフォルダへ保存し、次回は変更分を自動で重ねて表示します。</span></button><button className="save-option" disabled={saving} onClick={()=>save('overwrite')}><strong>② 管理中のPDFに上書き</strong><span>手書きを埋め込み、選択したフォルダへ保存します。資料IDは維持します。</span></button><button className="save-option" disabled={saving} onClick={()=>save('copy')}><strong>③ 編集済みコピーを作成</strong><span>元の資料を残し、新しいPDFを選択したフォルダに追加します。</span></button><p className="save-warning">②③は通常時の色で埋め込みます。埋め込んだ線の再編集・暗記切り替えはできません。</p></>:<><p>現在の手書きを埋め込んだPDFを、アプリ外へ書き出します。アプリ内のPDFと下書きは変更しません。</p><p className="save-warning">{isNativeApp()?'端末のファイル保存画面で保存先を選択できます。':'保存場所はブラウザの設定に従います。保存先を毎回選ぶ場合は、ブラウザのダウンロード設定を変更してください。'}</p><button className="primary full" disabled={saving||exportPreparing||!exportBlob} onClick={saveExternal}>保存先を選んでPDFを保存</button><p className="save-warning">暗記マーカーは通常時の色で埋め込みます。テキストメモはPDFには含めません。</p></>}
  {saveTarget==='external'&&exportPreparing&&<p role="status">編集済みPDFを作成・確認しています…</p>}{saveNotice&&<p role="status">{saveNotice}</p>}{saveError&&<p className="explorer-error" role="alert">{saveError}</p>}{saving?<p role="status">PDFを保存しています…</p>:<button className="text-btn" onClick={()=>setSaveDialog(false)}>キャンセル</button>}</section></div>}

 </div>
}
