import {cleanName,extension,assertParent,assertUnique,uniqueName,assertMove,descendants,entryFromDoc,docFromEntry,timestamp,formatSize} from './library-model.js';
let dbPromise;
const stores=['files','annotations','drafts','library','entries'];
function openDB(){return dbPromise??=new Promise((resolve,reject)=>{const req=indexedDB.open('folio-pdf',3);req.onupgradeneeded=()=>{for(const store of stores)if(!req.result.objectStoreNames.contains(store)){const os=req.result.createObjectStore(store,store==='entries'?{keyPath:'id'}:undefined);if(store==='entries')os.createIndex('parentId','parentId')}};req.onsuccess=()=>{req.result.onversionchange=()=>{req.result.close();dbPromise=null};resolve(req.result)};req.onerror=()=>{dbPromise=null;reject(req.error)}})}
export async function read(store,id){const db=await openDB();return new Promise((resolve,reject)=>{const req=db.transaction(store).objectStore(store).get(id);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
export async function write(store,id,value){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).put(value,id);tx.oncomplete=resolve;tx.onabort=()=>reject(tx.error)})}
export async function remove(store,id){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(store,'readwrite');tx.objectStore(store).delete(id);tx.oncomplete=resolve;tx.onabort=()=>reject(tx.error)})}
function fastDraft(id){try{return JSON.parse(localStorage.getItem('folio-draft-'+id))}catch{return null}}
export async function readDraft(id){const durable=await read('drafts',id),fast=fastDraft(id);return fast&&(!durable||fast.updatedAt>=durable.updatedAt)?fast:durable}
export function clearFastDraft(id){try{localStorage.removeItem('folio-draft-'+id)}catch{}}
function snapshot(entries){return {entries,docs:entries.filter(e=>e.type==='file').map(docFromEntry)}}
function persist(tx,before,after){const old=new Map(before.map(e=>[e.id,e])),current=new Set(after.map(e=>e.id));for(const e of after)if(old.get(e.id)!==e)tx.objectStore('entries').put(e);for(const e of before)if(!current.has(e.id))tx.objectStore('entries').delete(e.id);tx.objectStore('library').put(snapshot(after).docs,'docs')}
// Keep the old docs projection for the existing viewer and migrate all related data without changing IDs.
export async function initializeLibrary(fallback=[]){const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(stores,'readwrite');let result;const marker=tx.objectStore('library').get('treeVersion');marker.onsuccess=()=>{if(marker.result===1){const req=tx.objectStore('entries').getAll();req.onsuccess=()=>result=snapshot(req.result)}else{const req=tx.objectStore('library').get('docs');req.onsuccess=()=>{const entries=[];for(const doc of req.result||fallback){const e=entryFromDoc(doc);e.name=uniqueName(entries,e.name,e.parentId);entries.push(e)}persist(tx,[],entries);tx.objectStore('library').put(1,'treeVersion');result=snapshot(entries)}}};tx.oncomplete=()=>resolve(result);tx.onabort=()=>reject(tx.error)})}
async function mutate(action){await initializeLibrary();const db=await openDB();return new Promise((resolve,reject)=>{const tx=db.transaction(stores,'readwrite'),req=tx.objectStore('entries').getAll();let result,failure,afterCommit=()=>{};req.onsuccess=()=>{try{const before=req.result,outcome=action(before,tx);persist(tx,before,outcome.entries);result={...snapshot(outcome.entries),...outcome.result};afterCommit=outcome.afterCommit||afterCommit}catch(error){failure=error;tx.abort()}};tx.oncomplete=()=>{afterCommit();resolve(result)};tx.onabort=()=>reject(failure||tx.error||Error('保存に失敗しました。'))})}
export const listLibrary=()=>initializeLibrary();
export function createFolder(parentId,name){return mutate(entries=>{assertParent(entries,parentId);name=cleanName(name);assertUnique(entries,name,parentId);const time=timestamp(),entry={id:crypto.randomUUID(),name,type:'folder',parentId,createdAt:time,updatedAt:time};return {entries:[...entries,entry],result:{entry}}})}
export function renameEntry(id,baseName){return mutate(entries=>{const old=entries.find(e=>e.id===id);if(!old)throw Error('項目が見つかりません。');const ext=old.type==='file'?extension(old.name):'';const name=cleanName(cleanName(baseName)+ext);assertUnique(entries,name,old.parentId,id);const entry={...old,name,updatedAt:timestamp()};return {entries:entries.map(e=>e.id===id?entry:e),result:{entry}}})}
export function moveEntry(id,parentId){return mutate(entries=>{assertMove(entries,id,parentId);return {entries:entries.map(e=>e.id===id?{...e,parentId,updatedAt:timestamp()}:e)}})}
export function updateDocument(id,patch){return mutate(entries=>{const safe={};for(const key of ['star','note','course','category'])if(key in patch)safe[key]=patch[key];return {entries:entries.map(e=>e.id===id?{...e,...safe,updatedAt:timestamp()}:e)}})}
export function deletePdf(id){return mutate((entries,tx)=>{const ids=descendants(entries,id);for(const key of ids)for(const store of ['files','annotations','drafts'])tx.objectStore(store).delete(key);return {entries:entries.filter(e=>!ids.has(e.id)),afterCommit:()=>{for(const key of ids)clearFastDraft(key)}}})}
export function duplicateEntry(id){return mutate((entries,tx)=>{const source=entries.find(e=>e.id===id);if(!source)throw Error('項目が見つかりません。');const ids=descendants(entries,id),mapping=new Map([...ids].map(key=>[key,crypto.randomUUID()])),time=timestamp();const copies=entries.filter(e=>ids.has(e.id)).map(e=>{const newId=mapping.get(e.id);const copy={...e,id:newId,name:e.id===id?uniqueName(entries,e.name,e.parentId,true):e.name,parentId:e.id===id?e.parentId:mapping.get(e.parentId),createdAt:time,updatedAt:time};if(e.type==='file'){copy.storage={...e.storage,key:newId};for(const store of ['files','annotations','drafts']){const req=tx.objectStore(store).get(e.id);req.onsuccess=()=>{let value=req.result;if(store==='drafts'){const fast=fastDraft(e.id);if(fast&&(!value||fast.updatedAt>=value.updatedAt))value=fast}if(value!==undefined&&value!==null)tx.objectStore(store).put(value,newId)}}}return copy});return {entries:[...entries,...copies],result:{entry:copies.find(e=>e.id===mapping.get(id))}}})}
export async function importPdf(doc,blob){const outcome=await mutate((entries,tx)=>{const parentId=doc.parentId??null;assertParent(entries,parentId);const entry=entryFromDoc({...doc,createdAt:timestamp(),updatedAt:timestamp(),sizeBytes:blob.size});entry.name=uniqueName(entries,cleanName(entry.name),parentId);tx.objectStore('files').put(blob,entry.id);return {entries:[entry,...entries],result:{entry}}});return outcome.docs}
export function saveEdition(doc,mode,pages,note,blob,options={}){return mutate((entries,tx)=>{const current=entries.find(e=>e.id===doc.id);if(!current)throw Error('元の資料が削除されています。');if((current.revision||'legacy')!==(doc.revision||'legacy'))throw Error('別の画面でPDFが更新されました。開き直してから保存してください。');const copy=mode==='copy',parentId=options.parentId===undefined?current.parentId:options.parentId;assertParent(entries,parentId);const id=copy?crypto.randomUUID():doc.id,revision=crypto.randomUUID(),time=timestamp();const requestedName=options.name===undefined?undefined:cleanName(options.name);if(requestedName&&!/\.pdf$/i.test(requestedName))throw Error('PDFの拡張子は変更できません。');let name=copy?uniqueName(entries,requestedName||current.name.replace(/\.pdf$/i,'')+'（編集済み）.pdf',parentId):requestedName||current.name;if(!copy)assertUnique(entries,name,parentId,id);const target={...current,id,name,parentId,note,revision,updatedAt:time,createdAt:copy?time:current.createdAt};if(blob){Object.assign(target,{data:undefined,storedPdf:true,mimeType:'application/pdf',sizeBytes:blob.size,sizeLabel:formatSize(blob.size),storage:{provider:'indexeddb',key:id}});tx.objectStore('files').put(blob,id)}tx.objectStore('annotations').put({version:1,coordinateSpace:'normalized-page',revision,pages:mode==='delta'?pages:{}},id);tx.objectStore('drafts').delete(doc.id);return {entries:copy?[target,...entries]:entries.map(e=>e.id===id?target:e),result:{doc:docFromEntry(target)},afterCommit:()=>clearFastDraft(doc.id)}})}
