import {test,expect} from '@playwright/test';
import {PDFDocument} from 'pdf-lib';
import {readFile} from 'node:fs/promises';
import {pdfFixture} from './fixtures';
async function prepare(page){await page.goto('http://localhost:5173');await page.getByRole('button',{name:'資料を追加',exact:true}).click();await page.locator('input[type=file]').setInputFiles({name:'external.pdf',mimeType:'application/pdf',buffer:pdfFixture()});await page.getByRole('button',{name:'追加する',exact:true}).click();await expect(page.locator('.pdf-bottom')).toContainText('1 / 2');await expect(page.locator('.pdf-loading')).toHaveCount(0);const box=await page.locator('.annotation-canvas').boundingBox();await page.mouse.move(box.x+box.width*.2,box.y+box.height*.3);await page.mouse.down();await page.mouse.move(box.x+box.width*.6,box.y+box.height*.3,{steps:5});await page.mouse.up();await page.getByRole('button',{name:'編集を保存',exact:true}).click();await page.getByRole('button',{name:'アプリ外のフォルダ',exact:true}).click()}
async function original(page){return page.evaluate(async()=>{const s=await import('/storage.js'),{entries}=await s.listLibrary(),file=entries.find(e=>e.storedPdf);return {count:entries.length,bytes:Array.from(new Uint8Array(await(await s.read('files',file.id)).arrayBuffer())),draft:await s.readDraft(file.id),ink:await s.read('annotations',file.id)}})}
for(const picker of ['available','blocked','unsupported'])test(`default download works with ${picker} native picker`,async({page})=>{await page.addInitScript(mode=>{window.pickerCalls=0;window.showSaveFilePicker=mode==='unsupported'?undefined:()=>{window.pickerCalls++;throw Error('Native picker must not be called')}},picker);await prepare(page);const before=await original(page);await page.getByLabel('保存するファイル名').fill('書き出し用');await expect(page.getByRole('button',{name:'編集済みPDFをダウンロード',exact:true})).toHaveCount(0);const pending=page.waitForEvent('download');await page.getByRole('button',{name:'保存先を選んでPDFを保存',exact:true}).click();const download=await pending;expect(download.suggestedFilename()).toBe('書き出し用.pdf');const bytes=await readFile(await download.path());expect((await PDFDocument.load(bytes)).getPageCount()).toBe(2);expect(Array.from(bytes)).not.toEqual(before.bytes);expect(await page.evaluate(()=>window.pickerCalls)).toBe(0);expect(await original(page)).toEqual(before);await expect(page.getByRole('dialog',{name:'保存方法'})).toHaveCount(0);await expect(page.locator('.pdf-viewer').getByRole('alert')).toHaveCount(0)});
test('legacy title is safe for native OS picker and cleanup preserves the write error',async({page})=>{await prepare(page);const result=await page.evaluate(async()=>{const {externalStorage,externalPdfName}=await import('/external-storage.js');window.showSaveFilePicker=async options=>{window.safeName=options.suggestedName;return {createWritable:async()=>({write:async()=>{throw Error('original write error')},abort:async()=>{throw Error('cleanup error')}})}};const destination=await externalStorage.chooseDestination('授業/第1回:資料?.pdf');let message;try{await externalStorage.write(destination,new Blob(['test']))}catch(e){message=e.message}return {name:window.safeName,reserved:externalPdfName('CON.pdf'),message}});expect(result.name).toBe('授業_第1回_資料_.pdf');expect(result.reserved).toBe('_CON.pdf');expect(result.message).toBe('original write error')});

test('exported PDF reopens in Chrome app reader with original text and ink, without an error after success',async({page})=>{await page.addInitScript(()=>{window.showSaveFilePicker=async()=>{throw new DOMException('denied','NotAllowedError')}});await prepare(page);const pending=page.waitForEvent('download');await page.getByRole('button',{name:'保存先を選んでPDFを保存',exact:true}).click();const download=await pending,bytes=await readFile(await download.path());await expect(page.getByRole('dialog',{name:'保存方法'})).toHaveCount(0);await expect(page.locator('.pdf-viewer').getByRole('alert')).toHaveCount(0);await page.getByRole('button',{name:'PDFを閉じる',exact:true}).click();await page.getByRole('button',{name:'資料を追加',exact:true}).click();await page.locator('input[type=file]').setInputFiles({name:'reopened.pdf',mimeType:'application/pdf',buffer:bytes});await page.getByRole('button',{name:'追加する',exact:true}).click();await expect(page.locator('.pdf-bottom')).toContainText('1 / 2');await expect(page.locator('.pdf-loading')).toHaveCount(0);const color=await page.locator('.pdf-sheet>canvas').first().evaluate(c=>Array.from(c.getContext('2d').getImageData(c.width*.4,c.height*.3,1,1).data));expect(color.slice(0,3)).toEqual([36,75,63]);await expect(page.locator('.pdf-viewer').getByRole('alert')).toHaveCount(0)});
test('PDF generation failure occurs before the native picker can create an empty file',async({page})=>{await page.addInitScript(()=>{window.pickerCalls=0;window.showSaveFilePicker=async()=>{window.pickerCalls++;throw Error('must not open')}});await prepare(page);await expect(page.getByRole('button',{name:'保存先を選んでPDFを保存',exact:true})).toBeEnabled();await page.getByRole('dialog',{name:'保存方法'}).getByRole('button',{name:'キャンセル',exact:true}).click();await page.evaluate(()=>{HTMLCanvasElement.prototype.toDataURL=()=>{throw Error('画像変換失敗')}});await page.getByRole('button',{name:'編集を保存',exact:true}).click();await expect(page.getByRole('dialog').getByRole('alert')).toContainText('PDFを作成できませんでした');await expect(page.getByRole('button',{name:'保存先を選んでPDFを保存',exact:true})).toBeDisabled();expect(await page.evaluate(()=>window.pickerCalls)).toBe(0)});
