import {mkdtemp,writeFile,readFile,rm,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,extname} from 'node:path';
import {pathToFileURL} from 'node:url';
import {spawn} from 'node:child_process';
import sharp from 'sharp';
import {officeExecutable} from './office-runtime.mjs';
import {PDFDocument} from 'pdf-lib';
export const supported=new Set(['.pdf','.jpg','.jpeg','.png','.webp','.doc','.docx','.ppt','.pptx','.xls','.xlsx']);
export class ConversionError extends Error {constructor(message,status=422){super(message);this.status=status}}
function runOffice(args){return new Promise((resolve,reject)=>{const child=spawn(officeExecutable(),args,{stdio:['ignore','ignore','pipe'],detached:process.platform!=='win32'});let timedOut=false;const timer=setTimeout(()=>{timedOut=true;try{if(process.platform==='win32')child.kill('SIGKILL');else process.kill(-child.pid,'SIGKILL')}catch{}},60000);child.stderr.resume();child.once('error',e=>{clearTimeout(timer);reject(new ConversionError(e.code==='ENOENT'?'変換サーバーにLibreOfficeがありません。サーバーのセットアップが必要です。':'変換エンジンを起動できませんでした。',503))});child.once('close',code=>{clearTimeout(timer);if(timedOut)reject(new ConversionError('変換が60秒以内に完了しませんでした。',504));else if(code!==0)reject(new ConversionError('Officeファイルを変換できませんでした。'));else resolve()})})}
export async function convert(buffer,filename){const ext=extname(filename).toLowerCase();if(!supported.has(ext))throw new ConversionError('対応していないファイル形式です。',415);if(buffer.length===0||buffer.length>50*1024*1024)throw new ConversionError('ファイルは50 MB以下にしてください。',413);
if(ext==='.pdf'){try{await PDFDocument.load(buffer);return buffer}catch{throw new ConversionError('PDFが破損しているか、パスワードで保護されています。')}}
if(['.jpg','.jpeg','.png','.webp'].includes(ext)){try{const {data,info}=await sharp(buffer,{limitInputPixels:40000000,failOn:'error'}).rotate().png().toBuffer({resolveWithObject:true});const pdf=await PDFDocument.create(),image=await pdf.embedPng(data);const scale=Math.min(1,14400/Math.max(info.width,info.height));pdf.addPage([info.width*scale,info.height*scale]).drawImage(image,{x:0,y:0,width:info.width*scale,height:info.height*scale});return Buffer.from(await pdf.save())}catch{throw new ConversionError('画像を読み込めませんでした。画像形式とサイズを確認してください。')}}
const legacy=['.doc','.ppt','.xls'].includes(ext);if(legacy?!buffer.subarray(0,8).equals(Buffer.from('d0cf11e0a1b11ae1','hex')):buffer.subarray(0,2).toString()!=='PK')throw new ConversionError('ファイルの内容と拡張子が一致しません。');
const dir=await mkdtemp(join(tmpdir(),'folio-convert-'));try{const profile=join(dir,'profile');await mkdir(join(profile,'user'),{recursive:true});await writeFile(join(profile,'user','registrymodifications.xcu'),'<?xml version="1.0"?><oor:items xmlns:oor="http://openoffice.org/2001/registry"><item oor:path="/org.openoffice.Office.Common/Security/Scripting"><prop oor:name="MacroSecurityLevel" oor:op="fuse"><value>3</value></prop></item></oor:items>');const input=join(dir,'source'+ext);await writeFile(input,buffer);await runOffice([`-env:UserInstallation=${pathToFileURL(profile).href}`,'--headless','--nologo','--nodefault','--norestore','--convert-to','pdf','--outdir',dir,input]);let output;try{output=await readFile(join(dir,'source.pdf'));await PDFDocument.load(output)}catch{throw new ConversionError('変換できませんでした。破損・パスワード保護を確認してください。')}if(output.length>100*1024*1024)throw new ConversionError('変換後のPDFが100 MBを超えています。',413);return output}finally{await rm(dir,{recursive:true,force:true})}}
