import {officeHealth} from './office-runtime.mjs';
import express from 'express';import multer from 'multer';import {pathToFileURL,fileURLToPath} from 'node:url';import {convert} from './convert.mjs';
export const app=express();app.disable('x-powered-by');let active=0;const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:50*1024*1024,files:1,fields:0,parts:1}});
// Native WebViews use fixed local origins. Additional web clients must be explicit.
const allowedOrigins=new Set(['capacitor://localhost','https://localhost',...(process.env.FOLIO_ALLOWED_ORIGINS||'').split(',').map(s=>s.trim()).filter(Boolean)]);
app.use('/api',(req,res,next)=>{const origin=req.get('origin');const sameOrigin=!origin||origin===`${req.protocol}://${req.get('host')}`;if(!sameOrigin&&!allowedOrigins.has(origin))return res.status(403).json({error:'この接続元からのリクエストは許可されていません。'});if(origin){res.set('Access-Control-Allow-Origin',origin);res.vary('Origin')}if(req.method==='OPTIONS'){res.set({'Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type','Access-Control-Max-Age':'600'});return res.sendStatus(204)}next()});
app.get('/api/health',async(_,res)=>res.json({status:'ok',office:await officeHealth()}));
app.post('/api/convert',(req,res,next)=>{if(active>=2)return res.status(429).json({error:'変換サーバーが混み合っています。少し待って再試行してください。'});active++;let released=false;const release=()=>{if(!released){active--;released=true}};req.releaseConversion=release;next()},upload.single('file'),async(req,res)=>{try{if(!req.file)return res.status(400).json({error:'ファイルを選択してください。'});const pdf=await convert(req.file.buffer,req.file.originalname);res.set({'Content-Type':'application/pdf','Content-Disposition':'attachment; filename="converted.pdf"','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}).send(pdf)}catch(e){res.status(e.status||500).json({error:e.status?e.message:'変換中にエラーが発生しました。'})}finally{req.releaseConversion?.()}});
app.use((error,req,res,next)=>{req.releaseConversion?.();res.status(error.code==='LIMIT_FILE_SIZE'?413:400).json({error:error.code==='LIMIT_FILE_SIZE'?'ファイルは50 MB以下にしてください。':'アップロードを受け付けられませんでした。'})});
const dist=fileURLToPath(new URL('../dist/',import.meta.url));app.use(express.static(dist));app.get('/{*path}',(_,res)=>res.sendFile('index.html',{root:dist}));
if(process.argv[1]&&import.meta.url===pathToFileURL(process.argv[1]).href){app.listen(Number(process.env.PORT||3001),process.env.HOST||'127.0.0.1',()=>{console.log(`folio: http://localhost:${process.env.PORT||3001} (API / built app)`);officeHealth().then(health=>console.log(health.available?'Word変換: PDF生成を確認済み':health.message))})}
